config/routes.rb
Rails.application.routes.draw do

  get '/' => 'application#index'

  get '/:id' => 'application#show', as: :event

  get '/:id/members' => 'application#members', as: :members

  get '/:id/workers' => 'application#workers', as: :workers

  get '/:id/sponsors' => 'application#sponsors', as: :sponsors

  get '/:id/incomings' => 'application#incomings', as: :incomings
  get '/:id/outcomings' => 'application#outcomings', as: :outcomings
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :place

  has_and_belongs_to_many :workers
  has_and_belongs_to_many :members
  has_and_belongs_to_many :sponsors

  has_many :incomings
  has_many :outcomings
end

app/models/events_member.rb
class EventsMember < ActiveRecord::Base
  belongs_to :event
  belongs_to :member
end

app/models/events_sponsor.rb
class EventsSponsor < ActiveRecord::Base
  belongs_to :event
  belongs_to :sponsor
end

app/models/events_worker.rb
class EventsWorker < ActiveRecord::Base
  belongs_to :event
  belongs_to :worker
end

app/models/incoming.rb
class Incoming < ActiveRecord::Base
  belongs_to :sponsor
end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/outcoming.rb
class Outcoming < ActiveRecord::Base
  belongs_to :event
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
end

app/models/worker.rb
class Worker < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    @events = Event.paginate(:page => params[:page])
  end

  def show
    @event = Event.find params[:id]
  end

  def incomings
    @event = Event.find params[:id]
    @incomings = @event.incomings
  end

  def outcomings
    @event = Event.find params[:id]
    @outcomings = @event.outcomings
  end

  def members
    @event = Event.find params[:id]
    @members = @event.members
  end

  def workers
    @event = Event.find params[:id]
    @workers = @event.workers
  end

  def sponsors
    @event = Event.find params[:id]
    @sponsors = @event.sponsors
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/incomings.html.erb
<h3>Список доходов</h3>
<br>
<ol>
  <% @incomings.each do |x| %>
  <li>
    Сумма: <%= x.sum %> <br>
  </li>
  <% end %>
</ol>

app/views/application/index.html.erb
<h2>Список событий</h2>
<ol>
  <% @events.each do |event| %>
    <li><%= link_to event.title, event_path(event) %></li>
  <% end %>
</ol>

<%= will_paginate @events %>

app/views/application/members.html.erb
<h3>Список участников</h3>
<br>
<ol>
  <% @members.each do |x| %>
  <li>
    ФИО: <%= x.fio %> <br>
    Телефон: <%= x.phone %> <br>
  </li>
  <% end %>
</ol>

app/views/application/outcomings.html.erb
<h3>Список расходов</h3>
<br>
<ol>
  <% @outcomings.each do |x| %>
  <li>
    Сумма: <%= x.sum %> <br>
    Объект: <%= x.object %>
  </li>
  <% end %>
</ol>

app/views/application/show.html.erb
<h2><%= @event.title %></h2>
<h4>
  Место события:
  <%= @event.place.try :name %>
</h4>
<h4>
  Время события:
  <%= @event.date %>
</h4>

<h3>Детальная информация</h3>
<ul>
  <li><%= link_to "Работники", workers_path(@event) %></li>
  <li><%= link_to "Участники", members_path(@event) %></li>
  <li><%= link_to "Доходы", incomings_path(@event) %></li>
  <li><%= link_to "Расходы", outcomings_path(@event) %></li>
  <li><%= link_to "Спонсоры", sponsors_path(@event) %></li>
</ul>

app/views/application/sponsors.html.erb
<h3>Список спонсоров</h3>
<br>
<ol>
  <% @sponsors.each do |x| %>
  <li>
    Название компании: <%= x.company_name %> <br>
    Телефон: <%= x.phone %>
  </li>
  <% end %>
</ol>

app/views/application/workers.html.erb
<h3>Список работников</h3>
<br>
<ol>
  <% @workers.each do |x| %>
  <li>
    ФИО: <%= x.fio %> <br>
    Телефон: <%= x.phone %> <br>
    Роль: <%= x.role %>
  </li>
  <% end %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClientDb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= nav_bar brand: "Главная", brand_link: '/'  %>
  <div class="container">
    <%= yield %>
  </div>


</body>
</html>